on:
  push:
    tags:
      - 'v*'
name: Action for releases
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: amd64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0' # The Go version to download (if necessary) and use.
      - name: build
        run: |
            go mod tidy
            mkdir build && cd build
            go build ../
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.goos }} ${{ matrix.goarch }}
          path: build/*
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*